# Arquivo de allowlist para o Gitleaks
# Este arquivo contém padrões que devem ser ignorados pela detecção de segredos

[[rules]]
    description = "Exemplos de código e testes"
    regex = '''(?i)(example|test|sample|mock|demo|placeholder)'''
    tags = ["example", "test"]

[[rules]]
    description = "Comentários e documentação"
    regex = '''(?i)(TODO|FIXME|NOTE|HACK|XXX)'''
    tags = ["comment", "documentation"]

[[rules]]
    description = "Variáveis de ambiente de exemplo"
    regex = '''(?i)(env|environment)[_-]?(example|sample|demo|test)'''
    tags = ["environment", "example"]

[[rules]]
    description = "URLs públicas conhecidas"
    regex = '''https?://(localhost|127\.0\.0\.1|example\.com|test\.com|demo\.com)'''
    tags = ["url", "public"]

[[rules]]
    description = "Chaves de teste conhecidas"
    regex = '''(?i)(test|demo|example|sample)[_-]?(key|token|secret|password)'''
    tags = ["test", "demo", "example"]
